# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderGradient = rgba(aba8d7ff) rgba(7f86b8ff) rgba(a19eceff) rgba(7575aaff) rgba(9895c7ff) rgba(a9accbff) rgba(b2afe1ff) rgba(7a829aff) rgba(e7e6f5ff) 45deg
$inactiveBorderColor = rgba(7a829aaa)
$inactiveShadowColor = rgb(000000)
$activeShadowColor =  rgb(000000)

windowrule = opacity 1.0 override, match:class ^(brave-youtube\\.com__-Default)$
windowrule = opacity 1.0 override, match:class ^(chrome-youtube\\.com__-Default)$

general {
    col.active_border = $activeBorderGradient
    col.inactive_border = $inactiveBorderColor
    border_size = 4
    gaps_in = 8
    gaps_out = 12
}
group {
    col.border_active = $activeBorderGradient
}

decoration {
    # Use round window corners
    rounding = 8
    rounding_power = 4
    active_opacity = 0.85
    inactive_opacity = 0.78
    blur {
        enabled = true
        size = 4
        passes = 2
        noise = 0.16
    }
    shadow {
        enabled = true
        range = 22
        render_power = 6
        offset = 2 2
        # removed in Hyprland 0.56: ignore_window = true
        color = $activeShadowColor
        color_inactive = $inactiveShadowColor
    }
}

animations {
    bezier = easeInOutQuant, 0.76, 0, 0.24, 1
    bezier = linear, 0, 0, 1, 1

    animation = border, 1, 20, default
    animation = borderangle, 1, 55, linear, loop


  }
